spring:
 application:
  name: my-retail
 profiles: default
 cloud:
  config:
   enabled:false
 data:
  mongodb:
   database: RetailDatabase
   port: 27017
 api-docs:
  path: /api-docs
 security:
  user:
   name: rajender
   password: pandu
   
springdoc:
 swagger-ui:
  path:/swagger-ui-index.html
server:
 port: 8081
 servlet:
  context-path: /target/v1 
redsky-api-properties:
 red-sky-api-service-url: https://redsky.target.com

jwt:
 signing:
  key:
   secret: mySecret
 get:
  token:
   uri: /authenticate
 refresh:
  token:
   uri: /refresh
 http:
  request:
   header: Authorization
 token:
  expiration:
   in:
    seconds: 604800  
    
logging:
 level:
  org:
   springframework: debug
   